const transferStates = {
  SEND_PENDING: 'SEND_PENDING',
  SEND_DIRECT_TRANSFER_PENDING: 'SEND_DIRECT_TRANSFER_PENDING',
  SEND_FAILURE: 'SEND_FAILURE',
  SEND_DIRECT_TRANSFER_FAILURE: 'SEND_DIRECT_TRANSFER_FAILURE',
  SEND_DIRECT_TRANSFER_CONFIRMED: 'SEND_DIRECT_TRANSFER_CONFIRMED',

  SEND_CONFIRMED_RECEIVE_PENDING: 'SEND_CONFIRMED_RECEIVE_PENDING',
  SEND_CONFIRMED_RECEIVE_FAILURE: 'SEND_CONFIRMED_RECEIVE_FAILURE',
  SEND_CONFIRMED_RECEIVE_CONFIRMED: 'SEND_CONFIRMED_RECEIVE_CONFIRMED',
  SEND_CONFIRMED_RECEIVE_NOT_INITIATED: 'SEND_CONFIRMED_RECEIVE_NOT_INITIATED',

  SEND_CONFIRMED_EXPIRED_RECEIVE_PENDING: 'SEND_CONFIRMED_EXPIRED_RECEIVE_PENDING',
  SEND_CONFIRMED_EXPIRED_RECEIVE_FAILURE: 'SEND_CONFIRMED_EXPIRED_RECEIVE_FAILURE',
  SEND_CONFIRMED_EXPIRED_RECEIVE_CONFIRMED: 'SEND_CONFIRMED_EXPIRED_RECEIVE_CONFIRMED',
  SEND_CONFIRMED_EXPIRED_RECEIVE_NOT_INITIATED: 'SEND_CONFIRMED_EXPIRED_RECEIVE_NOT_INITIATED',

  SEND_CONFIRMED_RECEIVE_EXPIRED: 'SEND_CONFIRMED_RECEIVE_EXPIRED',
  SEND_CONFIRMED_CANCEL_PENDING: 'SEND_CONFIRMED_CANCEL_PENDING',
  SEND_CONFIRMED_CANCEL_CONFIRMED: 'SEND_CONFIRMED_CANCEL_CONFIRMED',
  SEND_CONFIRMED_CANCEL_FAILURE: 'SEND_CONFIRMED_CANCEL_FAILURE',

  SEND_CONFIRMED_EXPIRED_RECEIVE_EXPIRED: 'SEND_CONFIRMED_EXPIRED_RECEIVE_EXPIRED',
  SEND_CONFIRMED_EXPIRED_CANCEL_PENDING: 'SEND_CONFIRMED_EXPIRED_CANCEL_PENDING',
  SEND_CONFIRMED_EXPIRED_CANCEL_CONFIRMED: 'SEND_CONFIRMED_EXPIRED_CANCEL_CONFIRMED',
  SEND_CONFIRMED_EXPIRED_CANCEL_FAILURE: 'SEND_CONFIRMED_EXPIRED_CANCEL_FAILURE',

  UNKNOWN_STATE: 'UNKNOWN_STATE'
}

export default transferStates
